network:
   version: 2
   renderer: networkd
   ethernets:
     enp0s3:
        dhcp4: false
        dhcp6: false
        addresses: [192.168.1.195/24]
        gateway4: 192.168.1.1
        nameservers:
          search: [example.com,example.net,example.edu]
          addresses: [192.168.1.1, 8.8.8.8, 8.8.4.4]
